# Generated by Django 4.2.1 on 2023-09-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_productvariation_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
