# Generated by Django 4.2.1 on 2023-09-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_address_ordereditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
