# Generated by Django 4.2.1 on 2023-09-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_alter_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='products',
            field=models.ManyToManyField(to='shop_app.productvariation'),
        ),
    ]
