# Generated by Django 4.2.1 on 2023-09-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_alter_ordereditem_date_alter_ordereditem_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='products',
            field=models.ManyToManyField(to='shop_app.cartitem'),
        ),
    ]
