# Generated by Django 4.2.1 on 2023-09-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_alter_ordereditem_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'men'), ('Women', 'women'), ('Accessories', 'accessories'), ('Shoes', 'shoes'), ('Watches', 'watches'), ('Bag', 'bag')], max_length=20),
        ),
    ]
