# Generated by Django 4.2.1 on 2023-09-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_order_delete_cartitem_alter_ordereditem_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='products',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop_app.order'),
        ),
    ]
