# Generated by Django 4.2.1 on 2023-09-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0017_remove_ordereditem_products_ordereditem_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='productv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='products',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.order'),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.productvariation'),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
